# DAY 2 TASK

## IMPORT THE LIBRARY AND LOAD DATASET

In [2]:
import pandas as pd

nav_history = pd.read_csv("../data/raw/02_nav_history.csv")
transactions = pd.read_csv("../data/raw/08_investor_transactions.csv")
performance = pd.read_csv("../data/raw/07_scheme_performance.csv")
fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

### check the column and head of nav_history

In [3]:
print(nav_history.columns)
print(nav_history.head())

Index(['amfi_code', 'date', 'nav'], dtype='object')
   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

### Clean nav_history.csv

#### Check missing values

In [51]:
print(nav_history.isnull().sum())

amfi_code    0
date         0
nav          0
dtype: int64

#### Convert date to datetime

In [53]:
nav_history["date"] = pd.to_datetime(nav_history["date"])
nav_history["date"]

5750    2022-01-03
5751    2022-01-04
5752    2022-01-05
5753    2022-01-06
5754    2022-01-07
           ...
45995   2026-05-25
45996   2026-05-26
45997   2026-05-27
45998   2026-05-28
45999   2026-05-29
Name: date, Length: 46000, dtype: datetime64[ns]

#### Sort by fund and date

In [54]:
nav_history = nav_history.sort_values(
    ["amfi_code", "date"]
)
nav_history

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
5751      100016 2022-01-04  515.0971
5752      100016 2022-01-05  521.7239
5753      100016 2022-01-06  515.7880
5754      100016 2022-01-07  515.1639
...          ...        ...       ...
45995     149324 2026-05-25  292.4810
45996     149324 2026-05-26  291.2707
45997     149324 2026-05-27  288.8007
45998     149324 2026-05-28  280.6873
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

#### Remove duplicate rows

In [55]:
nav_history = nav_history.drop_duplicates()
nav_history

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
5751      100016 2022-01-04  515.0971
5752      100016 2022-01-05  521.7239
5753      100016 2022-01-06  515.7880
5754      100016 2022-01-07  515.1639
...          ...        ...       ...
45995     149324 2026-05-25  292.4810
45996     149324 2026-05-26  291.2707
45997     149324 2026-05-27  288.8007
45998     149324 2026-05-28  280.6873
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

#### Forward fill NAV values

In [57]:
nav_history["nav"] = nav_history.groupby(
    "amfi_code"
)["nav"].ffill()

nav_history["nav"]

5750     520.4608
5751     515.0971
5752     521.7239
5753     515.7880
5754     515.1639
           ...
45995    292.4810
45996    291.2707
45997    288.8007
45998    280.6873
45999    279.7511
Name: nav, Length: 46000, dtype: float64

#### Validate NAV > 0

In [58]:
invalid_nav = nav_history[
    nav_history["nav"] <= 0
]

print("Invalid NAV Records:")
print(len(invalid_nav))

Invalid NAV Records:
0

#### Save cleaned file

In [59]:
nav_history.to_csv(
    "../data/processed/nav_history_clean.csv",
    index=False
)

### check the column and head of transactions

In [49]:
print(transactions.columns)
print(transactions.head())

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='object')
  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              Sip        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              Sip         912
3   INV003436       2024-01-01     118634              Sip        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending

# Clean investor_transactions.csv

#### Check transaction types

In [18]:
print(
    transactions["transaction_type"]
    .value_counts()
)

transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

#### Standardize transaction types

In [21]:
transactions["transaction_type"] = (
    transactions["transaction_type"]
    .str.strip()
    .str.title()
)
transactions["transaction_type"]

0               Sip
1        Redemption
2               Sip
3               Sip
4           Lumpsum
            ...
32773       Lumpsum
32774           Sip
32775           Sip
32776           Sip
32777    Redemption
Name: transaction_type, Length: 32778, dtype: object

#### Fix dates

In [23]:
transactions["transaction_date"] = pd.to_datetime(
    transactions["transaction_date"]
)
transactions["transaction_date"]

0       2024-01-01
1       2024-01-01
2       2024-01-01
3       2024-01-01
4       2024-01-01
           ...
32773   2025-05-30
32774   2025-05-30
32775   2025-05-30
32776   2025-05-30
32777   2025-05-30
Name: transaction_date, Length: 32778, dtype: datetime64[ns]

#### Validate amount > 0

In [24]:
invalid_amount = transactions[
    transactions["amount_inr"] <= 0
]

print("Invalid Amount Rows:")
print(len(invalid_amount))

Invalid Amount Rows:
0

#### Check KYC values

In [25]:
print(
    transactions["kyc_status"]
    .value_counts()
)

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

#### Save cleaned file

In [26]:
transactions.to_csv(
    "../data/processed/investor_transactions_clean.csv",
    index=False
)

### check the column and head of performance

In [50]:
print(performance.columns)
print(performance.head())

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='object')
   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low

# Clean scheme_performance.csv

#### Check numeric columns

In [60]:
numeric_cols = [
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct",
    "benchmark_3yr_pct",
    "alpha",
    "beta",
    "sharpe_ratio",
    "sortino_ratio",
    "std_dev_ann_pct",
    "max_drawdown_pct",
    "aum_crore",
    "expense_ratio_pct"
]

#### Convert to numeric

In [61]:
for col in numeric_cols:
    performance[col] = pd.to_numeric(
        performance[col],
        errors="coerce"
    )
performance

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low
5,100016,HDFC Top 100 Fund - Regular Plan - Growth,HDFC Mutual Fund,Large Cap,Regular,10.94,14.84,11.32,14.06,0.78,0.97,1.06,1.70,14.0,-17.41,6434,1.55,5,Moderate
6,125497,HDFC Top 100 Fund - Direct Plan - Growth,HDFC Mutual Fund,Large Cap,Direct,11.48,13.38,13.48,12.25,1.13,0.97,0.96,1.45,14.0,-33.50,10611,0.92,4,Moderate
7,100033,HDFC Mid-Cap Opportunities Fund - Regular - Gr...,HDFC Mutual Fund,Mid Cap,Regular,15.43,16.58,17.69,15.63,0.95,0.91,0.87,1.44,19.0,-13.67,23185,1.38,5,High
8,125498,HDFC Mid-Cap Opportunities Fund - Direct - Growth,HDFC Mutual Fund,Mid Cap,Direct,19.98,15.29,15.85,14.39,0.90,1.04,0.80,1.38,19.0,-32.22,18792,0.78,4,High
9,100025,HDFC Short Term Debt Fund - Regular - Growth,HDFC Mutual Fund,Short Duration,Regular,6.83,7.37,6.41,5.39,1.98,0.44,1.84,2.79,4.0,-6.01,27953,0.56,3,Low
10,120503,ICICI Pru Bluechip Fund - Regular - Growth,ICICI Prudential MF,Large Cap,Regular,15.63,11.54,11.46,10.88,0.66,0.96,0.82,1.12,14.0,-25.91,36022,1.42,4,Moderate
11,120504,ICICI Pru Bluechip Fund - Direct - Growth,ICICI Prudential MF,Large Cap,Direct,14.12,14.41,13.02,13.53,0.88,1.03,1.03,1.27,14.0,-26.59,41553,0.80,3,Moderate
12,120505,ICICI Pru Midcap Fund - Regular - Growth,ICICI Prudential MF,Mid Cap,Regular,14.02,18.08,17.55,17.19,0.89,1.00,0.95,1.45,19.0,-21.84,979,1.36,3,High
13,120506,ICICI Pru Value Discovery Fund - Regular - Growth,ICICI Prudential MF,Value,Regular,16.67,14.76,12.60,14.21,0.55,0.92,0.98,1.50,15.0,-21.89,2571,1.41,4,Moderately High
14,120507,ICICI Pru Liquid Fund - Regular - Growth,ICICI Prudential MF,Liquid,Regular,8.89,7.68,7.94,5.83,1.85,0.26,7.68,10.37,0.5,-2.62,39116,0.74,5,Low
15,118632,Nippon India Large Cap Fund - Regular - Growth,Nippon India MF,Large Cap,Regular,15.84,14.00,14.70,13.14,0.86,0.88,1.00,1.68,14.0,-16.07,20909,1.51,4,Moderate
16,118633,Nippon India Large Cap Fund - Direct - Growth,Nippon India MF,Large Cap,Direct,14.42,12.33,14.72,10.63,1.70,1.02,0.88,1.48,14.0,-18.14,39475,0.72,3,Moderate
17,118634,Nippon India Small Cap Fund - Regular - Growth,Nippon India MF,Small Cap,Regular,21.30,20.15,21.88,19.35,0.80,1.03,0.81,1.14,25.0,-30.87,43630,1.53,4,Very High
18,118635,Nippon India ETF Nifty 50 BeES,Nippon India MF,Index/ETF,Direct,10.14,11.77,12.31,9.97,1.80,1.04,0.91,1.24,13.0,-26.75,20284,0.89,5,Moderate
19,118636,Nippon India Gilt Securities Fund - Regular - ...,Nippon India MF,Gilt,Regular,6.19,5.31,8.71,4.42,0.89,0.37,1.33,2.38,4.0,-2.23,30030,0.55,4,Low
20,120841,Kotak Bluechip Fund - Regular - Growth,Kotak Mahindra MF,Large Cap,Regular,14.37,12.25,13.42,10.98,1.27,0.93,0.87,1.34,14.0,-17.86,35585,1.59,3,Moderate
21,120842,Kotak Emerging Equity Fund - Regular - Growth,Kotak Mahindra MF,Mid Cap,Regular,17.12,18.23,17.75,16.32,1.91,1.00,0.96,1.27,19.0,-21.92,47469,1.56,4,High
22,120843,Kotak Flexicap Fund - Regular - Growth,Kotak Mahindra MF,Flexi Cap,Regular,15.74,15.65,13.50,13.80,1.85,0.95,0.98,1.57,16.0,-19.50,35012,1.45,5,Moderately High
23,120844,Kotak Liquid Fund - Regular - Growth,Kotak Mahindra MF,Liquid,Regular,4.26,6.18,8.26,4.66,1.52,0.47,6.18,9.70,0.5,-3.81,27623,0.60,3,Low
24,119092,Axis Bluechip Fund - Regular - Growth,Axis Mutual Fund,Large Cap,Regular,11.82,11.84,14.14,10.43,1.41,0.91,0.85,1.25,14.0,-27.54,25803,1.64,4,Moderate
25,119093,Axis Bluechip Fund - Direct - Growth,Axis Mutual Fund,Large Cap,Direct,13.95,12.14,13.66,10.71,1.43,0.87,0.87,1.54,14.0,-17.40,15866,0.75,4,Moderate
26,119094,Axis Midcap Fund - Regular - Growth,Axis Mutual Fund,Mid Cap,Regular,14.88,15.18,18.94,13.76,1.42,1.00,0.80,1.18,19.0,-32.38,28996,1.38,5,High
27,119095,Axis Small Cap Fund - Regular - Growth,Axis Mutual Fund,Small Cap,Regular,21.97,20.98,22.62,20.47,0.51,1.00,0.84,1.40,25.0,-14.45,21545,1.38,4,Very High
28,101206,ABSL Frontline Equity Fund - Regular - Growth,Aditya Birla Sun Life MF,Large Cap,Regular,14.82,13.78,12.86,12.44,1.34,1.03,0.98,1.25,14.0,-15.07,23500,1.60,5,Moderate
29,101207,ABSL Small Cap Fund - Regular - Growth,Aditya Birla Sun Life MF,Small Cap,Regular,24.93,22.38,23.80,20.54,1.84,0.97,0.90,1.47,25.0,-23.61,41613,1.53,5,Very High
30,101208,ABSL Liquid Fund - Regular - Growth,Aditya Birla Sun Life MF,Liquid,Regular,6.18,5.14,7.95,3.96,1.18,0.43,5.14,8.76,0.5,-3.66,38995,0.79,5,Low
31,102885,UTI Nifty 50 Index Fund - Regular - Growth,UTI Mutual Fund,Index,Regular,13.76,12.10,11.31,11.17,0.93,0.90,0.93,1.29,13.0,-24.42,7350,1.57,4,Moderate
32,102886,UTI Mid Cap Fund - Regular - Growth,UTI Mutual Fund,Mid Cap,Regular,16.30,15.61,15.86,14.49,1.12,0.92,0.82,1.21,19.0,-13.43,41728,1.51,5,High
33,102887,UTI Flexi Cap Fund - Regular - Growth,UTI Mutual Fund,Flexi Cap,Regular,17.43,15.34,15.78,13.55,1.79,1.00,0.96,1.37,16.0,-12.14,17912,1.64,5,Moderately High
34,148567,Mirae Asset Large Cap Fund - Regular - Growth,Mirae Asset MF,Large Cap,Regular,15.12,14.81,12.68,13.19,1.62,0.96,1.06,1.66,14.0,-17.07,11361,1.46,5,Moderate
35,148568,Mirae Asset Emerging Bluechip Fund - Regular -...,Mirae Asset MF,Large & Mid Cap,Regular,14.91,14.56,15.68,12.86,1.70,0.99,0.91,1.55,16.0,-33.15,49046,1.52,5,Moderately High
36,148569,Mirae Asset Tax Saver Fund - Regular - Growth,Mirae Asset MF,ELSS,Regular,11.16,13.58,14.26,13.04,0.54,0.98,0.80,1.03,17.0,-22.62,2989,1.60,5,High
37,149322,DSP Top 100 Equity Fund - Regular - Growth,DSP Mutual Fund,Large Cap,Regular,11.96,12.82,12.35,11.00,1.82,0.91,0.92,1.63,14.0,-21.70,41828,1.54,5,Moderate
38,149323,DSP Midcap Fund - Regular - Growth,DSP Mutual Fund,Mid Cap,Regular,14.12,17.16,19.00,16.14,1.02,0.98,0.90,1.50,19.0,-26.99,37835,1.61,4,High
39,149324,DSP Small Cap Fund - Regular - Growth,DSP Mutual Fund,Small Cap,Regular,20.20,20.08,20.61,19.39,0.69,0.98,0.80,1.23,25.0,-17.01,35124,1.52,4,Very High

#### Check missing values

In [62]:
print(
    performance[numeric_cols]
    .isnull()
    .sum()
)

return_1yr_pct       0
return_3yr_pct       0
return_5yr_pct       0
benchmark_3yr_pct    0
alpha                0
beta                 0
sharpe_ratio         0
sortino_ratio        0
std_dev_ann_pct      0
max_drawdown_pct     0
aum_crore            0
expense_ratio_pct    0
dtype: int64

#### Validate Expense Ratio

In [37]:
anomalies = performance[
    (performance["expense_ratio_pct"] < 0.1)
    |
    (performance["expense_ratio_pct"] > 2.5)
]

print(anomalies.shape)

(0, 19)

#### Save cleaned file

In [63]:
performance.to_csv(
    "../data/processed/scheme_performance_clean.csv",
    index=False
)

# INSTALL sqlalchemy LIBRARY

In [64]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\rohit\appdata\local\programs\python\python310\lib\site-packages (2.0.50)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\rohit\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\users\rohit\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.5.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

#### Create SQLite Database

In [41]:
from sqlalchemy import create_engine

engine = create_engine(
    "sqlite:///../bluestock_mf.db"
)

print("Database Created")

Database Created

#### Load Fund Dimension

In [42]:
fund_master.to_sql(
    "dim_fund",
    engine,
    if_exists="replace",
    index=False
)

40

#### Load NAV

In [65]:
nav_history.to_sql(
    "fact_nav",
    engine,
    if_exists="replace",
    index=False
)

46000

#### Load Transactions

In [44]:
transactions.to_sql(
    "fact_transactions",
    engine,
    if_exists="replace",
    index=False
)

32778

#### Load Performance

In [45]:
performance.to_sql(
    "fact_performance",
    engine,
    if_exists="replace",
    index=False
)

40

#### cleaning all the remaining dataset together

In [48]:
fund_master.to_csv(
    "../data/processed/fund_master_clean.csv",
    index=False
)

pd.read_csv("../data/raw/03_aum_by_fund_house.csv").to_csv(
    "../data/processed/aum_by_fund_house_clean.csv",
    index=False
)

pd.read_csv("../data/raw/04_monthly_sip_inflows.csv").to_csv(
    "../data/processed/monthly_sip_inflows_clean.csv",
    index=False
)

pd.read_csv("../data/raw/05_category_inflows.csv").to_csv(
    "../data/processed/category_inflows_clean.csv",
    index=False
)

pd.read_csv("../data/raw/06_industry_folio_count.csv").to_csv(
    "../data/processed/industry_folio_count_clean.csv",
    index=False
)

pd.read_csv("../data/raw/09_portfolio_holdings.csv").to_csv(
    "../data/processed/portfolio_holdings_clean.csv",
    index=False
)

pd.read_csv("../data/raw/10_benchmark_indices.csv").to_csv(
    "../data/processed/benchmark_indices_clean.csv",
    index=False
)

print("All processed files saved successfully.")

All processed files saved successfully.